[sample-microservice]
## comment or delete to include config
disabled = true

runCmd = "npm run start"
baseUrl = "/microservice/path/"

## uncomment when external dependency is deployed somewhere
# targetHost = "http://some.deployed.api/v1"

## uncomment when dev server is started on localhost
# targetPort = 4810

## uncomment if there is dependency on another build or project
# waitProject = "lib-dependency"
# waitFile = "dist/lib-dependency/package.json"
# waitDelay = 10000

## uncomment to show link on welcome page
# [[sample-microservice.urlShortcuts]]
# name = "page1"
# url = "/microservice/path/page1"

## uncomment to show link on welcome page
# [[sample-microservice.urlShortcuts]]
# name = "page2"
# url = "/microservice/path/page2"

## uncomment if there is dependency on another build or project
# [lib-dependency]
# rootDir = "../lib-dependency"
# runCmd = "npm run build-lib"
